### PR TITLE
Don't override maxWaitTimeout in job spec

### LINKED ISSUE #618: [BUG] maxWaitTimeout in job yml does not work
# Bug Description

## **Output of `kube-burner` version**
+ main
## **Describe the bug**
Job's `maxWaitTimeout` configuration does not work, `job.MaxWaitTimeout` is always 4h. 
```
level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:181"
```
https://github.com/kube-burner/kube-burner/pull/373 overrided `job.MaxWaitTimeout` in `newExecutorList`
```
                }
+               job.MaxWaitTimeout = timeout
                // Limits the number of workers to QPS and Burst
```

## **To Reproduce**

1. Set `maxWaitTimeout` in `examples/workloads/kubelet-density/kubelet-density.yml`
```
     waitWhenFinished: true
+    maxWaitTimeout: 10m
     podWait: false
```
2. Run `kube-burner init -c kubelet-density.yml`

## **Expected behavior**

Job's MaxWaitTimeout  is 10m.

## **Screenshots or output**

```
time="2024-04-16 10:28:44" level=info msg="🔥 Starting kube-burner (main@60acf057fa7557353bace58c30f9b21f1aba19e2) with UUID 5a3ebb81-0bfa-4555-b62d-1ba374925c14" file="job.go:99"
time="2024-04-16 10:28:44" level=info msg="📈 Registered measurement: podLatency" file="factory.go:78"
time="2024-04-16 10:28:44" level=info msg="Job kubelet-density: 25 iterations with 1 Pod replicas" file="create.go:94"
time="2024-04-16 10:28:44" level=info msg="QPS: 2" file="job.go:122"
time="2024-04-16 10:28:44" level=info msg="Burst: 2" file="job.go:123"
time="2024-04-16 10:28:44" level=info msg="Triggering job: kubelet-density" file="job.go:133"
time="2024-04-16 10:28:44" level=info msg="Creating Pod latency watcher for kubelet-density" file="pod_latency.go:153"
time="2024-04-16 10:28:44" level=info msg="2/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:45" level=info msg="4/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:46" level=info msg="6/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:47" level=info msg="8/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:48" level=info msg="10/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:49" level=info msg="12/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:50" level=info msg="14/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:51" level=info msg="16/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:52" level=info msg="18/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:53" level=info msg="20/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:54" level=info msg="22/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:55" level=info msg="24/25 iterations completed" file="create.go:132"
time="2024-04-16 10:28:56" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:181"
time="2024-04-16 10:28:58" level=info msg="Actions in namespace kubelet-density completed" file="waiters.go:80"
```

### PR DESCRIPTION
**Pull request by ZhangShuaiyi**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

+ Do not set default `job.MaxWaitTimeout` in `UnmarshalYAML`
+ Override `job.MaxWaitTimeout` only if it is empty

## Related Tickets & Documents

- Related Issue #
- Closes #618

### CODE REVIEW

File: pkg/burner/job.go [hunk 1]
```diff
@@ -318,7 +318,12 @@ func newExecutorList(configSpec config.Spec, kubeClientProvider *config.KubeClie
 				log.Fatalf("Job names must be unique: %s", job.Name)
 			}
 		}
-		job.MaxWaitTimeout = timeout
+		if job.MaxWaitTimeout == 0 {
+			log.Debugf("job.MaxWaitTimeout is zero, override by timeout:%s", timeout)
+			job.MaxWaitTimeout = timeout
+		} else {
+			log.Debugf("job.MaxWaitTimeout is non zero:%s", job.MaxWaitTimeout)
```
Comment (rsevilla87) [inline pkg/burner/job.go:325]:
```suggestion
			log.Debugf("job.MaxWaitTimeout is zero in %s, override by timeout: %s", job.Name, timeout)
			job.MaxWaitTimeout = timeout
		} else {
			log.Debugf("job.MaxWaitTimeout is non zero %s: %s", job.Name, job.MaxWaitTimeout)
```

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
Some small nits and lgtm :)

File: pkg/burner/job.go (hunk 1 above)
Comment (ZhangShuaiyi) [reply pkg/burner/job.go]: Done.
```
[root@devnode1 kubelet-density]# grep maxWaitTimeout kubelet-density.yml
    maxWaitTimeout: 10m
[root@devnode1 kubelet-density]# kube-burner --log-level debug init -c kubelet-density.yml 2>&1 | grep job.MaxWaitTimeout
time="2024-04-17 08:26:35" level=debug msg="job.MaxWaitTimeout is non zero in kubelet-density: 10m0s" file="job.go:325"
[root@devnode1 kubelet-density]# sed -i 's/maxWaitTimeout/#maxWaitTimeout/g' kubelet-density.yml
[root@devnode1 kubelet-density]# grep maxWaitTimeout kubelet-density.yml
    #maxWaitTimeout: 10m
[root@devnode1 kubelet-density]# kube-burner --log-level debug init -c kubelet-density.yml 2>&1 | grep job.MaxWaitTimeout
time="2024-04-17 08:27:24" level=debug msg="job.MaxWaitTimeout is zero in kubelet-density, override by timeout: 4h0m0s" file="job.go:322"
[root@devnode1 kubelet-density]#
```

**Review by rsevilla87 — APPROVED** [review]
lgtm, thanks!
