### PR TITLE
Directly delete non-namespaced resource

### LINKED ISSUE #630: [BUG] gc not work for non-namespaced resource
# Bug Description

## **Output of `kube-burner` version**

+ main

## **Describe the bug**

A create job for cluster level resources and enable gc, but this non-namespaced resource still exist after job finished.
```
[root@master-1 ~]# kubectl get clusterrole -l kube-burner-job=clusterrole-test
NAME                 CREATED AT
clusterrole-test-0   2024-04-23T03:26:39Z
clusterrole-test-1   2024-04-23T03:26:40Z
```

## **To Reproduce**

use yaml in https://github.com/kube-burner/kube-burner/issues/628

## **Expected behavior**

The clusterrole will be deleted after job finished.

## **Screenshots or output**

```
time="2024-04-23 03:29:50" level=info msg="🔥 Starting kube-burner (main@977573f98c890b5717a653ec7314a66fd72a8c59) with UUID 2b20ca16-9719-4529-aea1-c9091724fab6" file="job.go:99"
time="2024-04-23 03:29:50" level=debug msg="Preparing create job: clusterrole-test" file="create.go:46"
time="2024-04-23 03:29:50" level=debug msg="Rendering template: templates/clusterrole.yml" file="create.go:53"
time="2024-04-23 03:29:50" level=info msg="Job clusterrole-test: 2 iterations with 1 ClusterRole replicas" file="create.go:91"
time="2024-04-23 03:29:50" level=debug msg="job.MaxWaitTimeout is zero in clusterrole-test, override by timeout: 4h0m0s" file="job.go:320"
time="2024-04-23 03:29:50" level=info msg="Pre-load: images from job clusterrole-test" file="pre_load.go:45"
time="2024-04-23 03:29:50" level=info msg="No images found to pre-load, continuing" file="pre_load.go:51"
time="2024-04-23 03:29:50" level=info msg="QPS: 2" file="job.go:122"
time="2024-04-23 03:29:50" level=info msg="Burst: 2" file="job.go:123"
time="2024-04-23 03:29:50" level=info msg="Triggering job: clusterrole-test" file="job.go:133"
time="2024-04-23 03:29:50" level=info msg="Deleting non-namespace ClusterRole with selector kube-burner-job=clusterrole-test" file="namespaces.go:59"
time="2024-04-23 03:29:50" level=info msg="0/2 iterations completed" file="create.go:129"
time="2024-04-23 03:29:50" level=debug msg="Creating object replicas from iteration 0" file="create.go:132"
time="2024-04-23 03:29:50" level=debug msg="Creating object replicas from iteration 1" file="create.go:132"
time="2024-04-23 03:29:51" level=debug msg="Created ClusterRole/clusterrole-test-0" file="create.go:308"
I0423 03:29:52.095793  318956 request.go:697] Waited for 1.0001007s due to client-side throttling, not priority and fairness, request: POST:https://lb.test.local:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?timeout=1m0s
time="2024-04-23 03:29:52" level=debug msg="Created ClusterRole/clusterrole-test-1" file="create.go:308"
time="2024-04-23 03:29:52" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:178"
time="2024-04-23 03:29:52" level=info msg="Actions in namespace  completed" file="waiters.go:80"
time="2024-04-23 03:29:52" level=info msg="Verifying created objects" file="utils.go:85"
time="2024-04-23 03:29:52" level=info msg="clusterroles found: 2 Expected: 2" file="utils.go:118"
time="2024-04-23 03:29:52" level=info msg="Job clusterrole-test took 2s" file="job.go:197"
time="2024-04-23 03:29:52" level=info msg="Finished execution with UUID: 2b20ca16-9719-4529-aea1-c9091724fab6" file="job.go:276"
time="2024-04-23 03:29:52" level=info msg="Garbage collecting jobs" file="job.go:289"
time="2024-04-23 03:29:52" level=info msg="Deleting non-namespace ClusterRole with selector kube-burner-job=clusterrole-test" file="namespaces.go:59"
time="2024-04-23 03:29:53" level=info msg="👋 Exiting kube-burner 2b20ca16-9719-4529-aea1-c9091724fab6" file="kube-burner.go:84"
```

### PR DESCRIPTION
**Pull request by ZhangShuaiyi**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
+ `resourceInterface.Delete` is a non-blocked function.
+ If run `resourceInterface.Delete` in a goroutine, the `resourceInterface.Delete` haven't had a chance to run before `kube-burner` exit.

## Related Tickets & Documents

- Related Issue #
- Closes #630

### CODE REVIEW

File: pkg/util/namespaces.go [hunk 1]
```diff
@@ -127,12 +127,11 @@ func CleanupNonNamespacedResources(ctx context.Context, clientSet kubernetes.Int
 func DeleteNonNamespacedResources(ctx context.Context, resources *unstructured.UnstructuredList, resourceInterface dynamic.NamespaceableResourceInterface) {
 	if len(resources.Items) > 0 {
 		for _, item := range resources.Items {
-			go func(item unstructured.Unstructured) {
-				err := resourceInterface.Delete(ctx, item.GetName(), metav1.DeleteOptions{})
-				if err != nil {
-					log.Errorf("Error deleting %v/%v: %v", item.GetKind(), item.GetName(), err)
-				}
-			}(item)
+			log.Debugf("Deleting non-namespaced resource:%s", item.GetName())
```
Comment (rsevilla87) [inline pkg/util/namespaces.go:130]:
```suggestion
			log.Debugf("Deleting non-namespaced resource: %s", item.GetName())
```

Comment (ZhangShuaiyi) [reply pkg/util/namespaces.go]: Done

**Review by rsevilla87 — APPROVED** [review]
lgtm, thanks"
